uploads = []

[[generated]]
id = "_924ktx_5xmg5RKg7Ey83"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "ZeZoaasX9tAy5K8Zf_5ZH"
uri = "file://artifacts/mobile/coldverse-release-key.tar.gz"
type = "unspecified"
title = "coldverse-release-key.jks (tar.gz archive)"
